### ISSUE TITLE
Change lab's environment

### ISSUE THREAD

**Issue by AlekseiMaslakov** [BogdanMendli/java-labs-spbpu-2019-2020#1]
Здравствуйте
Перезалейте, пожалуйста, всё в виде мавен/градл проектов (возможно будет достаточно поправить gitignore), подключать все используемые либы руками очень не хочется :)

**Comment by BogdanMendli** [comment]
@AlekseiMaslakov, done

**Comment by BogdanMendli** [comment]
@AlekseiMaslakov, done 7 lab
